#!/usr/bin/env python
"""
Export OpenSCAD modules simply and in parallel.  Convert specific modules
in a .scad file to .stl and other OpenSCAD supported formats.

You may explicitly pass specific modules you wish to export, or you can simply
let this script search for "// make me" in your .scad file.

For instance:

$ cat > ./file.scad
    module mycylinder() {  // make me
      cylinder(r=10, h=1);
    }

$ ./openscad_exporter file.scad  # --> this generates mycylinder.stl


"""
import argparse
import atexit
from os.path import abspath, dirname, relpath
from os import getenv
import re
from subprocess import check_call, Popen
import tempfile


TEMPLATE = u"""
use <{fp}>;
{other_include}
{module}({args});
"""
REGEX = r'( *module *|.*\)|)([A-Za-z0-9_-]+)\((.*?)\) *(\{|;).*// *make me.*'
CMD = "{envvars} openscad -o {prefix}{module}{suffix}.{ftype} {tfp}"


def cleanup(proc, tfp):
    """Remove temp file created on exit"""
    proc.wait()
    check_call(['rm',  tfp])


def get_modules(fp):
    """Find all lines that have '// make me' defined and extract
    the module name and, if it is a called module, the parameters given
    """
    lines = open(fp, 'r').readlines()
    matches = [
        re.search(REGEX, line)
        for line in lines if re.match('.*// *make me.*', line)]
    assert matches, (
        "No modules found.  You should specify "
        " '// make me' on a module or when calling one")
    modules = [
        (x.group(2), x.group(3) if 'module' not in x.group(1) else '')
        for x in matches]
    return modules


def get_includes(fp):
    """Find all lines like `include  <xyz>` or `use <xyz>`"""
    pat = re.compile(r'^ *(include|use) *<(.*?)> *;')
    with open(fp, 'r') as fin:
        return [line for line in fin if re.match(pat, line)]


def main(ns):
    procs = {}
    for module, args in (ns.modules or get_modules(ns.fp)):
        # make temp scad file with relevant contents
        _, tfp = tempfile.mkstemp(
            prefix='openscad_%s_' % module, suffix='.scad')
        with open(tfp, 'w') as tfd:
            tfd.write(TEMPLATE.format(
                module=module, args=args, fp=ns.fp,
                other_include=''.join(get_includes(ns.fp))
            ))

        # run openscad on temp file
        _path = 'OPENSCADPATH=%s' % dirname(abspath(ns.fp))
        if ns.openscadpath:
            _path += ":%s" % relpath(ns.openscadpath, dirname(tfp))
        tcmd = CMD.format(module=module, ftype=ns.ftype, tfp=tfp,
                          envvars=_path, prefix=ns.prefix, suffix=ns.suffix)
        print(tcmd)
        p = Popen(tcmd, shell=True)
        procs[tcmd] = p
        atexit.register(cleanup, proc=p, tfp=tfp)

    if ns.block:
        for p in procs.values():
            p.wait()
        for tcmd, p in procs.items():
            if p.returncode:
                print('FAILED: %s, %s' % (tcmd, p.returncode))
                print(open(tfp).read())
                print("")

            else:
                print('Finished: %s, %s' % (tcmd, p.returncode))


def arg_parser():
    parser = argparse.ArgumentParser(description="""
Export OpenSCAD modules simply and in parallel.  Convert specific modules
in a .scad file to .stl and other OpenSCAD supported formats.

You may explicitly pass specific modules you wish to export, or you can simply
let this script search for "// make me" in your .scad file.
""")
    parser.add_argument(
        'fp', type=abspath, help="please supply a <file.scad>")
    parser.add_argument(
        '--ftype', default='stl',
        help="generate STL or other openscad supported file type")
    parser.add_argument(
        '--modules', default=[], nargs='+', type=lambda x: (x, ''),
        help='Comma separated list of modules to export to stl')
    parser.add_argument(
        '--openscadpath', default=getenv('OPENSCADPATH'),
        help="OPENSCADPATH lets you define where external libraries might be")
    parser.add_argument(
        '--block', action='store_true', help=(
            'Run in serial rather than in parallel.  '
            ' May take forever if you are compiling a lot of openscad modules'))
    parser.add_argument(
        '--prefix', default="",
        help=('Output filename starts with this string'))
    parser.add_argument(
        '--suffix', default="",
        help=('Output filename ends with this string'))
    return parser


if __name__ == '__main__':
    NS = arg_parser().parse_args()
    main(NS)
